print("Bithday dates\n")
tam=input("When is your birthday Tam? ")
jon=input("When is your birthday Jon? ")
Max=input("When is your birthday Max? ")
dev=input("When is your birthday Dev? ")
sam=input("When is your birthday Sam? ")
print("Tam's birthday",tam)
print("Jon's birthday",jon)
print("Max's birthday",Max)
print("Dev's birthday",dev)
print("Sam,s birthday",sam)